name: Nightly LoC Collection

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - feat/*

permissions:
  contents: write

jobs:
  collect-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: OctoTS/OctoTS-tools
          path: tools

      - name: Generate raw data
        run: |
          python3 tools/generateSampleData.py . --output temp.csv

      - name: Run OctoTS Action
        uses: OctoTS/OctoTS-action@feat/action-init
        with:
          format: pickle
          input: temp.csv
          output: metrics.pickle
          branch: metrics-data-1